### ISSUE TITLE
getting started typo

### ISSUE THREAD

**Issue by micuat** [baku89/glisp#12]
https://github.com/baku89/glisp/blame/master/docs/get-started.md#L11

I first thought 左上 is correct, but anyways the origin is at the center and +x is right, +y is down. I don't know what is a good way to describe this.

for example, doc in p5.js says

> (0,0) can be found at the top left with the positive direction to the right horizontally and down vertically.
-- https://p5js.org/learn/coordinate-system-and-shapes.html

so I will rephrase that (origin at center) in the english doc

**Comment by micuat** [comment]
https://github.com/baku89/glisp/blame/master/docs/get-started.md#L45

右上→左上

**Comment by micuat** [comment]
https://github.com/baku89/glisp/blame/master/docs/styles.md#L24

塗り→線のプロパティ

**Comment by micuat** [comment]
https://github.com/baku89/glisp/blame/master/docs/draw-tree.md#L20

ベタが来した→ベタ書きした

**Comment by baku89** [comment]
Sorry for checking the issue so late...! I had just merged the fixes :)
