### ISSUE TITLE
 Translation links in docs navbar broken

### ISSUE THREAD

**Issue by SnO2WMaN** [baku89/glisp#19]
現行のドキュメントのナビゲーションバー，Translationの部分のリンクの挙動は以下のように壊れています．

- **🇺🇸 English**をクリックする
  - `https://glisp.app/docs/#/en/` -> `https://glisp.app/docs/#/en/en/` -> `https://glisp.app/docs/#/en/en/en/`
- **🇯🇵 日本語**はクリックすることが出来ません

Docsifyには詳しくないので憶測ですが，https://docsify.now.sh/custom-navbar を参照するに以下のように修正すると良いのではないでしょうか．

https://github.com/baku89/glisp/blob/master/docs/_navbar.md
```markdown
- Translations
  - [🇺🇸 English](/en/)
  - [🇯🇵 日本語](/)
```

**Comment by baku89** [comment]
I just fixed the issue. そのとおりでした!
