### ISSUE TITLE
I have a question of syntax

### ISSUE THREAD

**Issue by kokiito** [baku89/glisp#37]
I'd like to use `loop` in glisp. 
Is `loop` currently available in glisp?

**Comment by baku89** [comment]
Thank you for your interest in my project and sponsoring me!

If you'd mean `loop`~`recur` special form in Clojure, I'm afraid that it has not been implemented yet at the present. 

The large part of the evaluator of Glisp is based on Mal (https://github.com/kanaka/mal) and it seems not to support `loop` as its syntax. I would like to know efficient implementation for this kind of recursion while avoiding maximum call stacks in JS compiler.

**Comment by s-ol** [comment]
@baku89 I'm not sure how the evaluator is implemented, but you can flatten the recursion with a loop. Here is an example loop from the clojure docs:
```clj
(loop [iter 1
       acc  0]
  (if (<= iter 10)
    (recur (inc iter) (+ acc iter))
    acc))
```

This could turn into recursion-free JS like this:

```
// declare loop state
let iter = 1;
let acc = 0;
let result;
while (true) {
  // inside of `(loop)` goes here

  if (iter <= 10) {
    // `(recur)` becomes `continue`
    // tuple-assign for atomic update
    // `(recur)` has to always be the last expression
    // in a branch of `(loop)`
    [iter, acc] = [iter+1, iter+acc];
    continue;
  } else {
    // if you reach the end of the loop without hitting
    // a "recur", leave the loop (with `break`)
    // here also the result may need to be processed.
    result = acc;
    break;
  }
}
```

If the loop is compiled to a function, instead of `break` and a `result` you can just `return` at the end of every branch.

**Comment by kokiito** [comment]
@baku89  @s-ol 
Thank you for responding.
I found out that Glisp comples Clojure to JS.

**Comment by baku89** [comment]
@s-ol I'm so appreciated for your advice!. Although the current implementation of Glisp does not generate JS code as you said, this approach may be useful to support recursive function calls!

**Comment by baku89** [comment]
@kokiito Yes, Glisp has quite a similar syntax and built-in functions to Clojure/ClojureScript, but not themselves. Here are the references FYI;)

https://glisp.app/docs/#/cheatsheet
https://glisp.app/docs/#/ref

And I've been reconsidering the whole syntax to enhance the affinity to visual programming/graphic design.

 - Haskell/Julia-like type system for type safeness and to determine proper UI for each expression before its evaluation.
 - Removes a notion of "order of execution". We can refer to variables and forms defined in the latter part of the code. 
 - A feature to refer to other expressions by relative path in AST structure without explicitly declaring a variable in common scope.
 - Incremental evaluation support. Glisp often needs to re-evaluate almost the same code in nearly 60fps, such as when you tweak the slider UI representing a number in the code. So the clever cache system is essential. 
 - All subtree of AST can be evaluated to a unique value with the least amount of calculation. (no need to execute the entire code to know the evaluated value of subtree)
 
But I think it's basically not so far from current Clojure-like syntax.

**Comment by kokiito** [comment]
@baku89 
Thank you for your response.
 I am interested in your response from two viewpoints.

- similar syntax and built-in functions to Clojure/ClojureScript.
  - I suppose Clojure/ClojureScript looks easy to be used by non-engineers.
- Glisp often needs to re-evaluate almost the same code in nearly 60fps
  - I think Glisp is good point to edit view from both of UI and codes. 60fps is the essential of Glisp.

**Comment by kokiito** [comment]
@baku89
Glisp is really so interesting software.  I will try to edit codes of Glisp and draw something on Glisp.

By the way, I like Scratch, what is a block-based visual programming language, because this language is designed to let you enjoy to create. I thought Glisp might have the same idea as Scratch.
