### ISSUE TITLE
docs: `Open in Editor` is not working.

### ISSUE THREAD

**Issue by zztkm** [baku89/glisp#55]
When I click on "open in editor", it takes me to a page like this link.

example:
- https://glisp.app/docs/#/en/get-started?id=draw-a-circle
- `Open in Editor`: https://glisp.app/stable/?code=%28circle+%5B50+50%5D+40%29

<img width="974" alt="スクリーンショット 2021-12-16 15 11 40" src="https://user-images.githubusercontent.com/33755694/146318400-4f5a1a32-a6a8-4c3d-a607-3de0ff1277e2.png">

clicked

<img width="1694" alt="スクリーンショット 2021-12-16 15 29 56" src="https://user-images.githubusercontent.com/33755694/146319883-c2b58783-c9ef-4b2c-8361-47be9f8412e1.png">

It is probably expected to go to the glisp editor screen, but currently it is not possible.

**Comment by zztkm** [comment]
memo: 

こいつか。
 https://glisp.app/stable/embed.html

**Comment by zztkm** [comment]
I was able to access it after modifying the link as follows.

- NG -> https://glisp.app/stable/?code=%28circle+%5B50+50%5D+40%29
- OK -> https://glisp.app/stable/embed.html?code=%28circle+%5B50+50%5D+40%29

**Comment by baku89** [comment]
Thank you for reporting. Once I thought it'd be useful to use `glisp.app/stable` as a link to the latest stable version, but in the directory, there's only embed.html (for docs) for now -- and the URL of 'Open in Editor' is dynamically calculated based on `location.href`. This might be why the link does not work.
