### ISSUE TITLE
`eval*` doesn't work properly in some cases

### ISSUE THREAD

**Issue by micuat** [baku89/glisp#6]
https://glisp.app/commit:69e6023/?code_url=https%3A%2F%2Fgist.githubusercontent.com%2Fmicuat%2Fa267b81b207787cc5aaed6a7656d3c86%2Fraw%2F07698838c485e05cf236ed3b312db2768edae342%2Fclampbug.glisp

this doesn't work
```lisp
(background "aliceblue")

(defvar x 100)
(defvar m0 0)
(defvar m1 100)
(transform (translate [(clamp x m0 m1) 74.29997253417969])
  (circle [0 0] 100)
)
```

this works
```lisp
(background "aliceblue")

(defvar x 100)
(defvar m0 0)
(defvar m1 100)
(circle [(clamp x m0 m1) 74.29997253417969] 100)
```

it used to work - and currently broken on both master and develop branches

**Comment by baku89** [comment]
Thanks! It seems a much more urgent issue relating to the core evaluator.
Simpler code to reproduce the error:

```
(def x 10)

(transform (translate [x 0])
	(circle [0 0] 100))
```

**Comment by baku89** [comment]
It might be related to the special form `eval*` I made for Glisp. It's used inside a function/macro but evaluates an expression in scope called the function/macro unlike the normal `eval` which always evaluates in a global scope.

```clojure
(defn test []
  (eval  '(prn "eval=" PI)) ; -> 3.14159
  (eval* '(prn "eval*=" PI))) ; -> 10

(def PI 10)
(test)
```

`graphics/transform` uses `eval*` inside its definition but it seems that the part inside `eval*` isn't bound to appropriate scope. I will try to resolve the problem as soon as possible.:)

**Comment by baku89** [comment]
Now your sketch would work :)

https://glisp.app/commit:198294a
